# Generated by Django 5.2.5 on 2025-08-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category'], 'verbose_name_plural': 'Services'},
        ),
    ]
